Added parallel processing and automatic window detection

diff --git a/x11-activity-session b/x11-activity-session
--- a/x11-activity-session
+++ b/x11-activity-session
@@ -1,7 +1,12 @@
 #!/usr/bin/env bash
 
-function printHelp(){
+function printDivider() {
+  local i
   for i in $(seq 1 $COLUMNS); do echo -n '─'; done; echo ''
+}
+
+function printHelp(){
+  printDivider
   echo -e 'How to use:'
   echo -e ''
   echo -e '\tx11-activity-session \e[1;31m-c \e[1;35m~/.mySession.json\e[1;30m # Starts the apps and positions them according to your session config \e[0m'
@@ -17,66 +22,61 @@ function printHelp(){
   echo -e '\t    {'
   echo -e '\t      "exec": "dolphin",'
   echo -e '\t      "position": "960,0",'
-  echo -e '\t      "size": "960,493",'
-  echo -e '\t      "detectionDelay": 0.5'
+  echo -e '\t      "size": "960,493"'
   echo -e '\t    },'
   echo -e '\t    {'
   echo -e '\t      "exec": "konsole",'
   echo -e '\t      "position": "960,523",'
-  echo -e '\t      "size": "960,493",'
-  echo -e '\t      "detectionDelay": 0.5'
+  echo -e '\t      "size": "960,493"'
   echo -e '\t    }'
   echo -e '\t  ]'
   echo -e '\t}'
   echo -e ''
-  for i in $(seq 1 $COLUMNS); do echo -n '─'; done; echo ''
+  printDivider
   exit 0
 }
 
-function startApp() {
-  local exec position size detectionDelay pid
-
-  exec="$1"
-  position="$2"
-  size="$3"
-  detectionDelay="$4"
-
-  pid=$(bash -c "$exec"'&>/dev/null & disown && echo $!')
-  sleep "$detectionDelay"
-  id=$(wmctrl -lp | grep "$pid" | awk '{print $1;}')
-  echo "$exec pid: $pid id: $id"
-
-  wmctrl -i -r "$id" -b 'remove,sticky'
-  wmctrl -i -r "$id" -b 'remove,maximized_horz'
-  wmctrl -i -r "$id" -b 'remove,maximized_vert'
-  wmctrl -i -r "$id" -e "1,$position,$size"
-}
-
 function checkDependencies() {
-  hash jq 2>/dev/null || { echo >&2 "This script requires jq but it's not installed. Aborting."; exit 1; }
-  hash wmctrl 2>/dev/null || { echo >&2 "This script requires wmctrl but it's not installed. Aborting."; exit 1; }
-  hash awk 2>/dev/null || { echo >&2 "This script requires awk but it's not installed. Aborting."; exit 1; }
+  hash jq 2>/dev/null || { echo -e >&2 "This script requires\e[1;31m jq\e[0m but it's not installed. Aborting."; exit 1; }
+  hash wmctrl 2>/dev/null || { echo -e >&2 "This script requires\e[1;31m wmctrl\e[0m but it's not installed. Aborting."; exit 1; }
+  hash awk 2>/dev/null || { echo -e >&2 "This script requires\e[1;31m awk\e[0m but it's not installed. Aborting."; exit 1; }
 }
 
 function main() {
-  local configJson
+  local configJson outDirectory i
   configJson="$1"
+  outDirectory="$(findmnt -cfn -o TARGET tmpfs)/x11-start-app-at-position-outputs"
+  i=0
+
+  [[ ! -d "$outDirectory" ]] && mkdir -p "$outDirectory"
 
   readarray -t apps < <(jq -c '.apps[]' "$configJson") #convert to bash arrays and remove trailing newline for each line (if any)
 
   IFS=$'\n' #read til newline
   for app in "${apps[@]}"; do
-    local exec position size detectionDelay
+    local exec position size
+    i=$((i + 1))
 
     exec=$(jq -r '.exec' <<< "${app}")
     position=$(jq -r '.position' <<< "${app}")
     size=$(jq -r '.size' <<< "${app}")
-    detectionDelay=$(jq '.detectionDelay' <<< "${app}")
 
-    echo "$exec at pos $position with size $size and detectionDelay $detectionDelay"
-    startApp "$exec" "$position" "$size" "$detectionDelay"
+    echo "$exec at pos $position with size $size"
+    ./x11-start-app-at-position.bash "$exec" "$position" "$size" >"$outDirectory/$i.out" 2>&1 &
   done
   unset IFS
+
+  wait
+  for ((j=1; j <= i; j++)); do
+    echo "┌─────┄"
+    while IFS= read -r line; do
+      echo "│ " "$line"
+    done <<< "$(cat "$outDirectory/$j.out")"
+    echo "└─────┄"
+  done
+
+  rm -r "$outDirectory"
+  exit 0
 }
 
 while getopts "hc:" OPT
